services:
  api:
    build: .
    image: workshop-management-api
    container_name: workshop-api
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    env_file: 
      - .env
    depends_on:
      - db_service
    
  db_service:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: 
  